[system]
db_driver = "sqlite"
db_path = "database/twse.db"
source_dir = "Source"
log_path = "log"
log_retention_days = 30
debug = false

[company]
api_endpoint = "/opendata/t187ap03_L"
schema_path = "database/init_company.sql"
table_name = "companies"
json_name = "listed_company.json"

[fund]
api_endpoint = "/opendata/t187ap47_L"
schema_path = "database/init_fund.sql"
table_name = "funds"
json_name = "fund.json"